name: Survival - Bug report
about: Create a report to help us improve
labels: 'Survival','bug'
body:
- type: textarea
  attributes:
    label: "Describe the bug"
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: "To Reproduce"
    description: Steps to reproduce the behavior.
  validations:
    required: true
- type: textarea
  attributes:
    label: "Time and Date"
    description: If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue.
  validations:
    required: false
- type: textarea
  attributes:
    label: "Screenshots/Videos"
    description: If applicable, add screenshots/videos to help explain your problem.
  validations:
    required: false
- type: textarea
  attributes:
    label: "Additional context"
    description: Add any other context about the problem here.
  validations:
    required: false
