name: Survival - Bug Report
description: File a bug report
labels: [Survival, bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: decription
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: input
    id: time-date
    attributes:
      label: Time and Date
      description: If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue
    validations:
      required: false
  - type: textarea
    id: screenshots-videos
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots/videos to help explain your problem
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
    validations:
      required: false
