- name: Assign to One Project
  uses: srggrs/assign-one-project-github-action@1.2.0
  with:
    # The url of the project to be assigned to.
    project: https://github.com/PirateCraft/dev/projects/1
    # The column name of the project, defaults to "To do" for issues and "In progress" for pull requests.
    column_name: # optional
